# Generated by Django 4.1 on 2023-09-04 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 4, 10, 40, 41, 210407)
            ),
        ),
    ]
