# Generated by Django 4.1 on 2023-10-04 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapis", "0003_alter_post_timestamp_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 19, 40, 36, 197653)
            ),
        ),
    ]
