# Generated by Django 4.1 on 2023-10-04 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapis", "0005_alter_post_timestamp_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 19, 45, 56, 88647)
            ),
        ),
    ]
