name: Run tests
on: push
name: Run tests
on: push
jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Execute tests
      env:
        DJANGO_SETTINGS_MODULE: mysite.settings
      run: pytest
